name: Install Certificate in Keychain
description: Install a single cert in existing keychain

inputs:
  KEYCHAIN:
    required: true
  KEYCHAIN_PASSWORD:
    required: true
  SIGNING_CERTIFICATE:
    required: true
  SIGNING_CERTIFICATE_P12_PASSWORD:
    required: true

runs:
  using: composite
  steps:
    - name: Install certificate
      shell: bash
      env:
        KEYCHAIN: ${{ inputs.KEYCHAIN }}
        KEYCHAIN_PASSWORD: ${{ inputs.KEYCHAIN_PASSWORD }}
        CERTIFICATE_PATH: /tmp/cert.p12
        SIGNING_CERTIFICATE: ${{ inputs.SIGNING_CERTIFICATE }}
        SIGNING_CERTIFICATE_P12_PASSWORD: ${{ inputs.SIGNING_CERTIFICATE_P12_PASSWORD }}
      run: |
        security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN
        echo "${SIGNING_CERTIFICATE}" | base64 --decode -o $CERTIFICATE_PATH
        security import $CERTIFICATE_PATH -k $KEYCHAIN -P "${SIGNING_CERTIFICATE_P12_PASSWORD}" -A -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
        rm $CERTIFICATE_PATH
        security find-identity -v $KEYCHAIN
        security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN
