name: Publish Custom App

on:
  release:
    types: [published]
    branches:
      - main

jobs:
  publish:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: custom

      - name: Set tag variable as an output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT  

      - name: Validate tag
        run: 
          |
          cd custom
          python src/tag_validator.py ${{ steps.vars.outputs.tag }}
          cd ..

      - name: Check-out kiwix/apple
        uses: actions/checkout@v4
        with:
          repository: kiwix/apple
          path: apple
          ref: main

      - name: Install Python dependencies for custom project generation
        run: python -m pip install pyyaml
      
      - name: Install Kiwix dependencies
        run:
          | 
          cd apple
          brew bundle 
          cd ..
      
      - name: Generate project based on tag
        env:
          DWDS_HTTP_BASIC_ACCESS_AUTHENTICATION: ${{ secrets.DWDS_HTTP_BASIC_ACCESS_AUTHENTICATION }}
        run:
          |
          # move the custom files under the same folder as the kiwix repo
          mv custom/ apple/
          cd apple/custom

          # make a custom copy of the Info.plist file
          cp ../Support/Info.plist Custom.plist

          python src/tag_validator.py ${{ steps.vars.outputs.tag }} | python src/generate_and_download.py

          # move the custom project file to the main folder
          mv custom_project.yml ../
          cd ..
          
          # run xcodegen on our custom project
          xcodegen -s custom_project.yml
          
          ls -la