name: Validate if we have all secrets set for building

on:
  pull_request:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if all required secrets were set
      run:
        |
        if [ -z "${{ secrets.APPLE_DEVELOPMENT_SIGNING_CERTIFICATE }}" ]; then
            echo "Error: APPLE_DEVELOPMENT_SIGNING_CERTIFICATE secret is not set."
        else
            echo "APPLE_DEVELOPMENT_SIGNING_CERTIFICATE is set."
        fi
        if [ -z "${{ secrets.APPLE_DEVELOPMENT_SIGNING_IDENTITY }}" ]; then
            echo "Error: APPLE_DEVELOPMENT_SIGNING_IDENTITY secret is not set."
        else
            echo "APPLE_DEVELOPMENT_SIGNING_IDENTITY is set."
        fi
        if [ -z "${{ secrets.APPLE_DEVELOPMENT_SIGNING_P12_PASSWORD }}" ]; then
            echo "Error: APPLE_DEVELOPMENT_SIGNING_P12_PASSWORD secret is not set."
        else
            echo "APPLE_DEVELOPMENT_SIGNING_P12_PASSWORD is set."
        fi
        if [ -z "${{ secrets.APPLE_DISTRIBUTION_SIGNING_CERTIFICATE }}" ]; then
            echo "Error: APPLE_DISTRIBUTION_SIGNING_CERTIFICATE secret is not set."
        else
            echo "APPLE_DISTRIBUTION_SIGNING_CERTIFICATE is set."
        fi
        if [ -z "${{ secrets.APPLE_DISTRIBUTION_SIGNING_P12_PASSWORD }}" ]; then
            echo "Error: APPLE_DISTRIBUTION_SIGNING_P12_PASSWORD secret is not set."
        else
            echo "APPLE_DISTRIBUTION_SIGNING_P12_PASSWORD is set."
        fi
        if [ -z "${{ secrets.APPLE_SIGNING_ALTOOL_PASSWORD }}" ]; then
            echo "Error: APPLE_SIGNING_ALTOOL_PASSWORD secret is not set."
        else
            echo "APPLE_SIGNING_ALTOOL_PASSWORD is set."
        fi
        if [ -z "${{ secrets.APPLE_SIGNING_ALTOOL_USERNAME }}" ]; then
            echo "Error: APPLE_SIGNING_ALTOOL_USERNAME secret is not set."
        else
            echo "APPLE_SIGNING_ALTOOL_USERNAME is set."
        fi
        if [ -z "${{ secrets.APPLE_SIGNING_TEAM }}" ]; then
            echo "Error: APPLE_SIGNING_TEAM secret is not set."
        else
            echo "APPLE_SIGNING_TEAM is set."
        fi
        if [ -z "${{ secrets.APPLE_STORE_AUTH_KEY }}" ]; then
            echo "Error: APPLE_STORE_AUTH_KEY secret is not set."
        else
            echo "APPLE_STORE_AUTH_KEY is set."
        fi
        if [ -z "${{ secrets.APPLE_STORE_AUTH_KEY_ID }}" ]; then
            echo "Error: APPLE_STORE_AUTH_KEY_ID secret is not set."
        else
            echo "APPLE_STORE_AUTH_KEY_ID is set."
        fi
        if [ -z "${{ secrets.APPLE_STORE_AUTH_KEY_ISSUER_ID }}" ]; then
            echo "Error: APPLE_STORE_AUTH_KEY_ISSUER_ID secret is not set."
        else
            echo "APPLE_STORE_AUTH_KEY_ISSUER_ID is set."
        fi
        if [ -z "${{ secrets.DWDS_HTTP_BASIC_ACCESS_AUTHENTICATION }}" ]; then
            echo "Error: DWDS_HTTP_BASIC_ACCESS_AUTHENTICATION secret is not set."
        else
            echo "DWDS_HTTP_BASIC_ACCESS_AUTHENTICATION is set."
        fi
